import { Event } from "@/lib/types";

export const events: Event[] = [
  {
    id: "spring-championship-2025",
    title: "Spring 8-Ball Championship",
    description:
      "Our biggest tournament of the season. Single elimination bracket, cash prizes for top 3 finishers. Open to all skill levels with handicap system applied.",
    date: "2025-04-19",
    time: "1:00 PM",
    endTime: "9:00 PM",
    type: "tournament",
    featured: true,
    registrationOpen: true,
    maxParticipants: 32,
    entryFee: 25,
    tags: ["tournament", "8-ball", "cash-prizes"],
  },
  {
    id: "wednesday-9ball-league",
    title: "Wednesday Night 9-Ball League",
    description:
      "Recurring weekly league every Wednesday. Teams of 2. Skill-based handicap system ensures fair competition for all levels. Season runs 12 weeks.",
    date: "2025-04-02",
    time: "7:00 PM",
    endTime: "10:00 PM",
    type: "league",
    featured: true,
    registrationOpen: true,
    maxParticipants: 24,
    entryFee: 10,
    tags: ["league", "9-ball", "weekly", "teams"],
  },
  {
    id: "friday-open-play",
    title: "Friday Open Play Night",
    description:
      "Casual open play every Friday. No reservation needed. Grab a table, rack 'em up, and enjoy the best billiards atmosphere in WNY.",
    date: "2025-04-04",
    time: "6:00 PM",
    endTime: "12:00 AM",
    type: "open-play",
    featured: false,
    registrationOpen: false,
    tags: ["open-play", "casual", "walk-in"],
  },
  {
    id: "beginners-clinic-april",
    title: "Beginner's Clinic — April",
    description:
      "New to billiards? Our certified instructor covers stance, grip, stroke mechanics, and basic strategy. Limited to 8 participants for personalized attention.",
    date: "2025-04-12",
    time: "11:00 AM",
    endTime: "1:00 PM",
    type: "special",
    featured: true,
    registrationOpen: true,
    maxParticipants: 8,
    entryFee: 35,
    tags: ["clinic", "beginner", "instruction"],
  },
  {
    id: "ladies-night-8ball",
    title: "Ladies Night — 8-Ball Tournament",
    description:
      "A dedicated evening celebrating women in billiards. Competitive 8-ball brackets, prizes, and an electric atmosphere.",
    date: "2025-04-26",
    time: "6:00 PM",
    endTime: "10:00 PM",
    type: "tournament",
    featured: false,
    registrationOpen: true,
    maxParticipants: 16,
    entryFee: 15,
    tags: ["tournament", "8-ball", "ladies-night"],
  },
  {
    id: "saturday-doubles-league",
    title: "Saturday Doubles League",
    description:
      "Partner up for this 10-week doubles league. Mixed formats including 8-ball and rotation. Great for building teamwork and competitive skills.",
    date: "2025-04-05",
    time: "2:00 PM",
    endTime: "6:00 PM",
    type: "league",
    featured: false,
    registrationOpen: true,
    maxParticipants: 20,
    entryFee: 15,
    tags: ["league", "doubles", "weekly"],
  },
];
