import { GalleryImage } from "@/lib/types";

export const galleryImages: GalleryImage[] = [
  {
    id: "1",
    src: "/gallery/table-vip-1.jpg",
    alt: "VIP one-piece slate table under warm lighting",
    caption: "Our flagship VIP one-piece slate table",
    category: "tables",
    featured: true,
  },
  {
    id: "2",
    src: "/gallery/tables-row-1.jpg",
    alt: "Row of premium Predator pool tables",
    caption: "Five Predator Diamond Pro tables ready for play",
    category: "tables",
    featured: true,
  },
  {
    id: "3",
    src: "/gallery/atmosphere-1.JPG",
    alt: "Pool Academy interior — warm ambient lighting",
    caption: "Premium atmosphere, every visit",
    category: "atmosphere",
    featured: true,
  },
  {
    id: "4",
    src: "/gallery/atmosphere-2.jpg",
    alt: "Close up of billiards cue on table",
    caption: "Precision in every detail",
    category: "atmosphere",
    featured: true,
  },
  {
    id: "5",
    src: "/gallery/event-tournament-1.jpg",
    alt: "Players competing in Pool Academy tournament",
    caption: "Spring Championship in action",
    category: "events",
    featured: true,
  },
  {
    id: "6",
    src: "/gallery/event-league-1.jpg",
    alt: "Wednesday night league players",
    caption: "Wednesday 9-Ball League night",
    category: "events",
    featured: false,
  },
  {
    id: "7",
    src: "/gallery/venue-exterior-1.jpg",
    alt: "Pool Academy entrance at night",
    caption: "Find us in the heart of Etobicoke",
    category: "venue",
    featured: false,
  },
  {
    id: "8",
    src: "/gallery/table-slate-1.jpg",
    alt: "Three-piece slate table close-up",
    caption: "Simonis cloth on our three-piece slate tables",
    category: "tables",
    featured: false,
  },
  {
    id: "9",
    src: "/gallery/atmosphere-3.jpg",
    alt: "Players enjoying casual open play",
    caption: "Open play — your schedule, your game",
    category: "atmosphere",
    featured: false,
  },
];
